user www-data;
worker_processes auto;
pid /run/nginx/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    types_hash_max_size 4096;
    server_tokens off;

    client_max_body_size 128M;

    access_log /dev/stdout;

    upstream php-fpm {
        server unix:/var/run/php-fpm.sock;
    }

    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /app/public;
        index index.php;

        location = /up {
            try_files /up @php;
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location @php {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /app/public/index.php;
            fastcgi_pass php-fpm;
        }

        location ~ \.php$ {
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_pass php-fpm;
            fastcgi_read_timeout 60;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}